[tasks.build]
command = "cargo"
args = [
    "build",
    "--example",
    "${@}"]

[tasks.build-all]
command = "cargo"
args = [
    "build",
    "--examples"
]

[tasks.renode-bin]
script = [
    "echo '$bin?'=@target/thumbv7em-none-eabihf/debug/examples/${@} > target/renode-bin.resc"
]

[tasks.run]
command = "renode"
args = [
    "renode/stm32f4.resc"
]
dependencies = ["build", "renode-bin"]

[tasks.test]
command = "renode-test"
args = [
    "integration-tests/${@}.robot",
    "-r",
    "test-results"
]
dependencies = ["build"]

[tasks.tests]
command = "renode-test"
args = [
    "-t",
    "integration-tests/tests.yaml",
    "-r",
    "test-results"
]
dependencies = ["build-all"]