name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: thumbv7em-none-eabihf
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
